// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
  show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdC9fcErInoIJMdwCh8fMV9eplzPEiHjo',
    appId: '1:1071626570093:web:a809aee197646f5093b264',
    messagingSenderId: '1071626570093',
    projectId: 'pbm2051',
    authDomain: 'pbm2051.firebaseapp.com',
    storageBucket: 'pbm2051.firebasestorage.app',
    measurementId: 'G-9HZPJZCM6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPlzJtvNFCbBelbSKRdEOZ3OLkHox8a9Y',
    appId: '1:1071626570093:android:3b563c2c9a91f92993b264',
    messagingSenderId: '1071626570093',
    projectId: 'pbm2051',
    storageBucket: 'pbm2051.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1kiUyi_CYyEt6MakuxNfyPz1D7nWuMX0',
    appId: '1:1071626570093:ios:351f157a5c4bacff93b264',
    messagingSenderId: '1071626570093',
    projectId: 'pbm2051',
    storageBucket: 'pbm2051.firebasestorage.app',
    iosBundleId: 'com.example.crudBengkel',
  );
}
